create table teste (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(255) not NULL,
    valor number(10,2) not null, 
    descricao varchar(255) not NULL
)

-- Inserção de 5 valores na tabela 'teste'
INSERT INTO teste (nome, valor, descricao) VALUES ('Produto A', 10.50, 'Descrição do Produto A');
INSERT INTO teste (nome, valor, descricao) VALUES ('Produto B', 20.00, 'Descrição do Produto B');
INSERT INTO teste (nome, valor, descricao) VALUES ('Produto C', 15.75, 'Descrição do Produto C');
INSERT INTO teste (nome, valor, descricao) VALUES ('Produto D', 30.10, 'Descrição do Produto D');
INSERT INTO teste (nome, valor, descricao) VALUES ('Produto E', 25.00, 'Descrição do Produto E');